// Generated by api.js
// DO NOT EDIT

import {createApi} from './request'

export const AuthRegisterApiV1 = createApi<AuthRegisterRequest,AuthRegisterResponse>('/admin/v1/auth/register')
export const AuthLoginApiV1 = createApi<AuthLoginRequest,AuthLoginResponse>('/admin/v1/auth/login')
export const AuthRefreshApiV1 = createApi<AuthRefreshTokenRequest,AuthRefreshTokenResponse>('/admin/v1/auth/refresh')
export const AuthLogoutApiV1 = createApi<void,AuthLogoutResponse>('/admin/v1/auth/logout')
export const AuthProfileApiV1 = createApi<void,AuthProfileResponse>('/admin/v1/auth/profile')
export const AuthMenusApiV1 = createApi<void,AuthMenusResponse>('/admin/v1/auth/menus')
export const SystemSettingCenterUsersCreateApiV1 = createApi<CenterUserCreateRequest,CenterUserCreateResponse>('/admin/v1/system-setting/center-users/create')
export const SystemSettingCenterUsersListApiV1 = createApi<CenterUserListRequest,CenterUserListResponse>('/admin/v1/system-setting/center-users/list')
export const SystemSettingCenterUsersUpdateApiV1 = createApi<CenterUserUpdateRequest,CenterUserUpdateResponse>('/admin/v1/system-setting/center-users/update')
export const SystemSettingCenterUsersDeleteApiV1 = createApi<CenterUserDeleteRequest,CenterUserDeleteResponse>('/admin/v1/system-setting/center-users/delete')
export const SystemSettingCenterUsersUpdateStatusApiV1 = createApi<CenterUserUpdateStatusRequest,CenterUserUpdateStatusResponse>('/admin/v1/system-setting/center-users/update-status')
export const SystemSettingCenterUsersAssignRolesApiV1 = createApi<CenterUserAssignRolesRequest,CenterUserAssignRolesResponse>('/admin/v1/system-setting/center-users/assign-roles')
export const SystemSettingRolesCreateApiV1 = createApi<RoleCreateRequest,RoleCreateResponse>('/admin/v1/system-setting/roles/create')
export const SystemSettingRolesListApiV1 = createApi<RoleListRequest,RoleListResponse>('/admin/v1/system-setting/roles/list')
export const SystemSettingRolesUpdateApiV1 = createApi<RoleUpdateRequest,RoleUpdateResponse>('/admin/v1/system-setting/roles/update')
export const SystemSettingRolesDeleteApiV1 = createApi<RoleDeleteRequest,RoleDeleteResponse>('/admin/v1/system-setting/roles/delete')
export const SystemSettingRolesUpdateStatusApiV1 = createApi<RoleUpdateStatusRequest,RoleUpdateStatusResponse>('/admin/v1/system-setting/roles/update-status')
export const SystemSettingRolesAssignMenusApiV1 = createApi<RoleAssignMenusRequest,RoleAssignMenusResponse>('/admin/v1/system-setting/roles/assign-menus')
export const SystemSettingMenusCreateApiV1 = createApi<MenuCreateRequest,MenuCreateResponse>('/admin/v1/system-setting/menus/create')
export const SystemSettingMenusListApiV1 = createApi<MenuListRequest,MenuListResponse>('/admin/v1/system-setting/menus/list')
export const SystemSettingMenusUpdateApiV1 = createApi<MenuUpdateRequest,MenuUpdateResponse>('/admin/v1/system-setting/menus/update')
export const SystemSettingMenusDeleteApiV1 = createApi<MenuDeleteRequest,MenuDeleteResponse>('/admin/v1/system-setting/menus/delete')
export const SystemSettingMenusUpdateStatusApiV1 = createApi<MenuUpdateStatusRequest,MenuUpdateStatusResponse>('/admin/v1/system-setting/menus/update-status')

export type AuthRegisterRequest = {
  username: string;
  email: string;
  password: string;
  first_name: string;
  last_name: string;
  phone_number: string;
}

export type AuthRegisterResponse = {
  code: number;
  message: string;
  data: object;
}

export type AuthLoginRequest = {
  username: string;
  password: string;
}

export type AuthLoginResponse = {
  code: number;
  message: string;
  data: object;
}

export type AuthRefreshTokenRequest = {
  refresh_token: string;
}

export type AuthRefreshTokenResponse = {
  code: number;
  message: string;
  data: object;
}

export type AuthLogoutResponse = {
  code: number;
  message: string;
  data: object;
}

export type AuthProfileResponse = {
  code: number;
  message: string;
  data: object;
}

export type AuthMenusResponse = {
  code: number;
  message: string;
  data: object;
}

export type CenterUserCreateRequest = {
  username: string;
  email: string;
  password: string;
  first_name: string;
  last_name: string;
  phone_number: string;
  avatar_url: string;
  status: string;
}

export type CenterUserCreateResponse = {
  code: number;
  message: string;
  data: object;
}

export type ListCenterUsersFilters = {
  id: number;
  username: string;
  email: string;
  phone_number: string;
  status: string;
  role_ids: number[];
  created_at_from: string;
  created_at_to: string;
}

export type CenterUserListRequest = {
  page: number;
  page_size: number;
  keyword: string;
  sort: object;
  filters: ListCenterUsersFilters;
}

export type CenterUserItem = {
  id: number;
  username: string;
  email: string;
  first_name: object;
  last_name: object;
  phone_number: object;
  avatar_url: object;
  status: string;
  last_login_at: object;
  created_at: string;
  updated_at: string;
}

export type CenterUserListResponse = {
  items: CenterUserItem[];
  total: number;
}

export type CenterUserUpdateRequest = {
  username: string;
  email: string;
  first_name: string;
  last_name: string;
  phone_number: string;
  avatar_url: string;
  status: string;
  id: number;
}

export type CenterUserUpdateResponse = {
  code: number;
  message: string;
  data: object;
}

export type CenterUserDeleteRequest = {
  id: number;
}

export type CenterUserDeleteResponse = {
  code: number;
  message: string;
  data: object;
}

export type CenterUserUpdateStatusRequest = {
  id: number;
  status: string;
}

export type CenterUserUpdateStatusResponse = {
  code: number;
  message: string;
  data: object;
}

export type CenterUserAssignRolesRequest = {
  user_id: number;
  role_ids: number[];
}

export type CenterUserAssignRolesResponse = {
  code: number;
  message: string;
  data: object;
}

export type RoleCreateRequest = {
  name: string;
  code: string;
  description: string;
  status: string;
}

export type RoleCreateResponse = {
  code: number;
  message: string;
  data: object;
}

export type ListRolesFilters = {
  id: number;
  name: string;
  code: string;
  status: string;
  menu_ids: number[];
  created_at_from: string;
  created_at_to: string;
}

export type RoleListRequest = {
  page: number;
  page_size: number;
  keyword: string;
  sort: object;
  filters: ListRolesFilters;
}

export type RoleItem = {
  id: number;
  name: string;
  code: string;
  description: object;
  status: string;
  created_at: string;
  updated_at: string;
}

export type RoleListResponse = {
  items: RoleItem[];
  total: number;
}

export type RoleUpdateRequest = {
  name: string;
  code: string;
  description: string;
  status: string;
  id: number;
}

export type RoleUpdateResponse = {
  code: number;
  message: string;
  data: object;
}

export type RoleDeleteRequest = {
  id: number;
}

export type RoleDeleteResponse = {
  code: number;
  message: string;
  data: object;
}

export type RoleUpdateStatusRequest = {
  id: number;
  status: string;
}

export type RoleUpdateStatusResponse = {
  code: number;
  message: string;
  data: object;
}

export type RoleAssignMenusRequest = {
  role_id: number;
  menu_ids: number[];
}

export type RoleAssignMenusResponse = {
  code: number;
  message: string;
  data: object;
}

export type MenuCreateRequest = {
  parent_id: number;
  code: string;
  // Multi-language labels
  labels: object;
  icon: string;
  route_path: string;
  sort_order: number;
  status: string;
  is_visible: boolean;
}

export type MenuCreateResponse = {
  code: number;
  message: string;
  data: object;
}

export type ListMenusFilters = {
  id: number;
  // null for root menus
  parent_id: object;
  code: string;
  status: string;
  is_visible: boolean;
  route_path: string;
  created_at_from: string;
  created_at_to: string;
}

export type MenuListRequest = {
  page: number;
  page_size: number;
  keyword: string;
  sort: object;
  filters: ListMenusFilters;
}

export type MenuItem = {
  id: number;
  parent_id: object;
  code: string;
  labels: object;
  icon: object;
  route_path: object;
  sort_order: number;
  status: string;
  is_visible: boolean;
  created_at: string;
  updated_at: string;
}

export type MenuListResponse = {
  items: MenuItem[];
  total: number;
}

export type MenuUpdateRequest = {
  parent_id: number;
  code: string;
  // Multi-language labels
  labels: object;
  icon: string;
  route_path: string;
  sort_order: number;
  status: string;
  is_visible: boolean;
  id: number;
}

export type MenuUpdateResponse = {
  code: number;
  message: string;
  data: object;
}

export type MenuDeleteRequest = {
  id: number;
}

export type MenuDeleteResponse = {
  code: number;
  message: string;
  data: object;
}

export type MenuUpdateStatusRequest = {
  id: number;
  status: string;
}

export type MenuUpdateStatusResponse = {
  code: number;
  message: string;
  data: object;
}
