// Generated by api.js
// DO NOT EDIT

import {createApi} from './index'

export const AuthRegisterApiV1 = createApi<AuthRegisterRequest,AuthRegisterResponse>('/admin/v1/auth/register')
export const AuthLoginApiV1 = createApi<AuthLoginRequest,AuthLoginResponse>('/admin/v1/auth/login')
export const AuthRefreshApiV1 = createApi<AuthRefreshTokenRequest,AuthRefreshTokenResponse>('/admin/v1/auth/refresh')
export const AuthLogoutApiV1 = createApi<void,AuthLogoutResponse>('/admin/v1/auth/logout')
export const AuthProfileApiV1 = createApi<void,AuthProfileResponse>('/admin/v1/auth/profile')
export const AuthMenusApiV1 = createApi<void,AuthMenusResponse>('/admin/v1/auth/menus')
export const SystemSettingCenterUsersCreateApiV1 = createApi<CenterUserCreateRequest,CenterUserCreateResponse>('/admin/v1/system-setting/center-users/create')
export const SystemSettingCenterUsersListApiV1 = createApi<CenterUserListRequest,CenterUserListResponse>('/admin/v1/system-setting/center-users/list')
export const SystemSettingCenterUsersUpdateApiV1 = createApi<CenterUserUpdateRequest,CenterUserUpdateResponse>('/admin/v1/system-setting/center-users/update')
export const SystemSettingCenterUsersDeleteApiV1 = createApi<CenterUserDeleteRequest,CenterUserDeleteResponse>('/admin/v1/system-setting/center-users/delete')
export const SystemSettingCenterUsersUpdateStatusApiV1 = createApi<CenterUserUpdateStatusRequest,CenterUserUpdateStatusResponse>('/admin/v1/system-setting/center-users/update-status')
export const SystemSettingCenterUsersAssignRolesApiV1 = createApi<CenterUserAssignRolesRequest,CenterUserAssignRolesResponse>('/admin/v1/system-setting/center-users/assign-roles')
export const SystemSettingCenterUsersUserBindRoleListApiV1 = createApi<UserBindRoleListRequest,UserBindRoleListResponse>('/admin/v1/system-setting/center-users/user-bind-role-list')
export const SystemSettingCenterUsersUpdatePasswordApiV1 = createApi<CenterUserUpdatePasswordRequest,CenterUserUpdatePasswordResponse>('/admin/v1/system-setting/center-users/update-password')
export const SystemSettingRolesCreateApiV1 = createApi<RoleCreateRequest,RoleCreateResponse>('/admin/v1/system-setting/roles/create')
export const SystemSettingRolesListApiV1 = createApi<RoleListRequest,RoleListResponse>('/admin/v1/system-setting/roles/list')
export const SystemSettingRolesUpdateApiV1 = createApi<RoleUpdateRequest,RoleUpdateResponse>('/admin/v1/system-setting/roles/update')
export const SystemSettingRolesDeleteApiV1 = createApi<RoleDeleteRequest,RoleDeleteResponse>('/admin/v1/system-setting/roles/delete')
export const SystemSettingRolesUpdateStatusApiV1 = createApi<RoleUpdateStatusRequest,RoleUpdateStatusResponse>('/admin/v1/system-setting/roles/update-status')
export const SystemSettingRolesAssignMenusApiV1 = createApi<RoleAssignMenusRequest,RoleAssignMenusResponse>('/admin/v1/system-setting/roles/assign-menus')
export const SystemSettingRolesRoleBindMenuListApiV1 = createApi<RoleBindMenuListRequest,RoleBindMenuListResponse>('/admin/v1/system-setting/roles/role-bind-menu-list')
export const SystemSettingMenusCreateApiV1 = createApi<MenuCreateRequest,MenuCreateResponse>('/admin/v1/system-setting/menus/create')
export const SystemSettingMenusListApiV1 = createApi<MenuListRequest,MenuListResponse>('/admin/v1/system-setting/menus/list')
export const SystemSettingMenusUpdateApiV1 = createApi<MenuUpdateRequest,MenuUpdateResponse>('/admin/v1/system-setting/menus/update')
export const SystemSettingMenusDeleteApiV1 = createApi<MenuDeleteRequest,MenuDeleteResponse>('/admin/v1/system-setting/menus/delete')
export const SystemSettingMenusUpdateStatusApiV1 = createApi<MenuUpdateStatusRequest,MenuUpdateStatusResponse>('/admin/v1/system-setting/menus/update-status')
export const SystemSettingMenusParentMenuMasterdataApiV1 = createApi<ParentMenuMasterdataRequest,ParentMenuMasterdataResponse>('/admin/v1/system-setting/menus/parent-menu/masterdata')

export type AuthRegisterRequest = {
  username: string;
  email: string;
  password: string;
  first_name: string;
  last_name: string;
  phone_number: string;
}

export type AuthRegisterResponse = {
  id: number;
  username: string;
  email: string;
  first_name: string;
  last_name: string;
  phone_number: string;
  avatar_url: string;
  status: string;
  last_login_at: string;
}

export type AuthLoginRequest = {
  username: string;
  password: string;
}

export type AuthLoginResponse = {
  access_token: string;
  refresh_token: string;
  expires_in: number;
}

export type AuthRefreshTokenRequest = {
  refresh_token: string;
}

export type AuthRefreshTokenResponse = {
  access_token: string;
  refresh_token: string;
  expires_in: number;
}

export type AuthLogoutResponse = {
  message: string;
}

export type AuthProfileResponse = {
  id: number;
  username: string;
  email: string;
  first_name: string;
  last_name: string;
  phone_number: string;
  avatar_url: string;
  status: string;
  last_login_at: string;
}

export type MultiLanguageText = {
  // English text
  en: string;
  // Khmer text
  kh: string;
}

export type MenuItemData = {
  id: number;
  parent_id: number;
  labels: MultiLanguageText;
  icon: string;
  route_path: string;
  sort_order: number;
  children: MenuItemData[];
}

export type AuthMenusResponse = {
  menus: MenuItemData[];
}

export type CenterUserCreateRequest = {
  username: string;
  email: string;
  password: string;
  first_name: string;
  last_name: string;
  phone_number: string;
  avatar_url: string;
  status: string;
}

export type CenterUserCreateResponse = {

}

export type SortDto = {
  field: string;
  order: string;
}

export type CenterUserListRequest = {
  page: number;
  page_size: number;
  sort: SortDto;
  id: number;
  username: string;
  email: string;
  phone_number: string;
  status: string;
  role_ids: number[];
  created_at_from: string;
  created_at_to: string;
}

export type CenterUserItem = {
  id: number;
  username: string;
  email: string;
  first_name: string;
  last_name: string;
  phone_number: string;
  avatar_url: string;
  status: string;
  last_login_at: string;
  created_at: string;
  updated_at: string;
}

export type CenterUserListResponse = {
  items: CenterUserItem[];
  total: number;
}

export type CenterUserUpdateRequest = {
  username: string;
  email: string;
  first_name: string;
  last_name: string;
  phone_number: string;
  avatar_url: string;
  status: string;
  id: number;
}

export type CenterUserUpdateResponse = {

}

export type CenterUserDeleteRequest = {
  id: number;
}

export type CenterUserDeleteResponse = {

}

export type CenterUserUpdateStatusRequest = {
  id: number;
  status: string;
}

export type CenterUserUpdateStatusResponse = {

}

export type CenterUserAssignRolesRequest = {
  user_id: number;
  role_ids: number[];
}

export type CenterUserAssignRolesResponse = {

}

export type UserBindRoleListRequest = {
  user_id: number;
}

export type UserBindRoleListResponse = {
  role_ids: number[];
}

export type CenterUserUpdatePasswordRequest = {
  id: number;
  new_password: string;
}

export type CenterUserUpdatePasswordResponse = {

}

export type RoleCreateRequest = {
  name: string;
  code: string;
  description: string;
  status: string;
}

export type RoleCreateResponse = {

}

export type RoleListRequest = {
  page: number;
  page_size: number;
  sort: SortDto;
  id: number;
  name: string;
  code: string;
  status: string;
  menu_ids: number[];
  created_at_from: string;
  created_at_to: string;
}

export type RoleItem = {
  id: number;
  name: string;
  code: string;
  description: string;
  status: string;
  created_at: string;
  updated_at: string;
}

export type RoleListResponse = {
  items: RoleItem[];
  total: number;
}

export type RoleUpdateRequest = {
  name: string;
  code: string;
  description: string;
  status: string;
  id: number;
}

export type RoleUpdateResponse = {

}

export type RoleDeleteRequest = {
  id: number;
}

export type RoleDeleteResponse = {

}

export type RoleUpdateStatusRequest = {
  id: number;
  status: string;
}

export type RoleUpdateStatusResponse = {

}

export type RoleAssignMenusRequest = {
  role_id: number;
  menu_ids: number[];
}

export type RoleAssignMenusResponse = {

}

export type RoleBindMenuListRequest = {
  role_id: number;
}

export type RoleBindMenuListResponse = {
  menu_ids: number[];
}

export type MenuCreateRequest = {
  parent_id: number;
  // Multi-language labels
  labels: MultiLanguageText;
  icon: string;
  route_path: string;
  sort_order: number;
  status: string;
  is_visible: boolean;
}

export type MenuCreateResponse = {

}

export type MenuListRequest = {
  page: number;
  page_size: number;
  sort: SortDto;
  id: number;
  // null for root menus
  parent_id: number;
  status: string;
  is_visible: boolean;
  route_path: string;
  created_at_from: string;
  created_at_to: string;
}

export type MenuItem = {
  id: number;
  parent_id: number;
  labels: MultiLanguageText;
  icon: string;
  route_path: string;
  sort_order: number;
  status: string;
  is_visible: boolean;
  created_at: string;
  updated_at: string;
}

export type MenuListResponse = {
  items: MenuItem[];
  total: number;
}

export type MenuUpdateRequest = {
  parent_id: number;
  // Multi-language labels
  labels: MultiLanguageText;
  icon: string;
  route_path: string;
  sort_order: number;
  status: string;
  is_visible: boolean;
  id: number;
}

export type MenuUpdateResponse = {

}

export type MenuDeleteRequest = {
  id: number;
}

export type MenuDeleteResponse = {

}

export type MenuUpdateStatusRequest = {
  id: number;
  status: string;
}

export type MenuUpdateStatusResponse = {

}

export type ParentMenuMasterdataRequest = {
  status: string;
}

export type ParentMenuMasterdataItem = {
  id: number;
  code: string;
  label: string;
}

export type ParentMenuMasterdataResponse = {
  items: ParentMenuMasterdataItem[];
}
