import { httpGet, camelCase, trimPrefix } from "./core.js";
import  { parse } from "yaml";
import { writeFileSync } from "fs";

let [apiName, prefix, apiUrl] = process.argv.slice(2);

const genFileDesc = {
  schemas: {},
  apis: {},
};

function render() {
  let tpl = `// Generated by api.js\n// DO NOT EDIT\n\n`;

  tpl += `import {createApi} from './index'\n\n`;
  // apis
  for (const [key, value] of Object.entries(genFileDesc.apis)) {
    tpl += value;
  }

  for (const [key, value] of Object.entries(genFileDesc.schemas)) {
    tpl += value;
  }
  // write to file
  console.log("write to file ", `${apiName}.ts`);
  writeFileSync(`${apiName}.ts`, tpl);
}

async function main() {
  const content = await httpGet(apiUrl);
  const doc = parse(content);

  const schemas = doc.components.schemas;
  for (const [key, value] of Object.entries(schemas)) {
    genFileDesc.schemas[key] = genSchema(key, value);
  }

  // paths
  const paths = doc.paths;
  for (const [key, value] of Object.entries(paths)) {
    genHttpApi(key, value);
  }
  render();
}

main();

function genHttpApi(path, desc) {
  const { get, post } = desc;

  // Check if post method exists
  if (!post) {
    console.warn(`No POST method defined for ${path}, skipping...`);
    return;
  }

  // Handle request body - some endpoints don't have requestBody (like logout, profile)
  let requestType = "void";
  const jsonRequest = post.requestBody?.content?.["application/json"];
  if (jsonRequest?.schema?.$ref) {
    requestType = trimPrefix(
      jsonRequest.schema.$ref,
      "#/components/schemas/"
    );
  }

  // Handle response - try 200, 201, or first available response
  let responseType = "unknown";
  const responses = post.responses;

  // Try common success status codes in order
  const statusCodes = ["200", "201", "204"];
  for (const statusCode of statusCodes) {
    const response = responses?.[statusCode];
    const responseContent = response?.content?.["application/json"];

    if (responseContent?.schema?.$ref) {
      responseType = trimPrefix(
        responseContent.schema.$ref,
        "#/components/schemas/"
      );
      break;
    }
  }

  // If no response type found, skip this endpoint
  if (responseType === "unknown") {
    console.warn(`No valid response schema found for ${path}, skipping...`);
    return;
  }

  // Generate the API
  let apiName = camelCase(trimPrefix(path, prefix));

  // Move "v1" or "V1" to the end with capital V
  apiName = apiName.replace(/^v(\d+)/, () => '');

  // Find version number and append it at the very end (after "Api")
  const versionMatch = trimPrefix(path, prefix).match(/^v(\d+)/i);
  const versionSuffix = versionMatch ? 'V' + versionMatch[1] : '';

  let api = `export const ${apiName}Api${versionSuffix} = createApi<${requestType},${responseType}>('${path}')\n`;
  genFileDesc.apis[path] = api;
}

function genSchema(key, value) {
  let r = "";
  r += getTsObject(key, value);
  return r;
}

function getTsObject(name, desc) {
  let ts = `\nexport type ${name.replace(".", "")} = {\n`;
  const { properties } = desc;

  if (properties) {
    let props = "";
    for (let [key, value] of Object.entries(properties)) {
      // clean up key eg: user_id，omitempty
      key = key.replace(/,\s*omitempty/g, "");
      if (key.endsWith("omitempty")) {
        console.log(key);
      }
      let comment = value.description ? `  // ${value.description}\n` : "";
      props += `${comment}  ${key}: ${getTsType(value)};\n`;
    }
    if (props) {
      ts += props.slice(0, -1);
    }
  }

  ts += "\n}\n";
  return ts;
}

function getTsType(property) {
  // Handle allOf pattern (used for composition/inheritance)
  if (property.allOf && Array.isArray(property.allOf)) {
    // Look for $ref in allOf array
    for (const item of property.allOf) {
      if (item.$ref) {
        const refType = item.$ref.split("/").pop();
        return refType.replace(".", "");
      }
    }
  }

  switch (property.type) {
    case "integer":
    case "bigint":
      return "number";
    case "array":
      let arrRef = property.items.$ref;
      if (arrRef) {
        let refType = arrRef.split("/").pop();
        switch (refType) {
          case "string":
          case "varchar":
            return "string[]";
          case "int":
          case "bigint":
            return "number[]";
        }
        return `${refType.replace(".", "")}[]`;
      }
      return `${getTsType(property.items)}[]`;
    case "string":
    case "varchar":
      return "string";
    case "bool":
    case "boolean":
      return "boolean";
    default:
      let objRef = property.$ref;
      if (objRef) {
        const refType = objRef.split("/").pop();
        if (refType === "") {
          return "any";
        }
        if (refType === "json.RawMessage") {
          return "any";
        }
        if (refType === "bool" || refType === "boolean") {
          return "boolean";
        }
        if (refType === "bigint") {
          return "number";
        }
        if (refType === "varchar") {
          return "string";
        }

        return refType.replace(".", "");
      }
      return property.type || "any";
  }
}

function getDefaultValue(property) {
  switch (property.type) {
    case "integer":
      return "0";
    case "array":
      return "[]";
    default:
      let objRef = property.$ref;
      if (objRef) {
        let name = objRef.split("/").pop();
        if (name === "json.RawMessage") {
          return "null";
        }
        return `create${name}()`;
      }
      return '""';
  }
}
