import { httpGet, camelCase, trimPrefix } from "./core.js";
import  { parse } from "yaml";
import { writeFileSync } from "fs";

let [apiName, prefix, apiUrl] = process.argv.slice(2);

const genFileDesc = {
  schemas: {},
  apis: {},
};

function render() {
  let tpl = `// Generated by api.js\n// DO NOT EDIT\n\n`;

  tpl += `import {createApi} from './request'\n\n`;
  // apis
  for (const [key, value] of Object.entries(genFileDesc.apis)) {
    tpl += value;
  }

  for (const [key, value] of Object.entries(genFileDesc.schemas)) {
    tpl += value;
  }
  // write to file
  console.log("write to file ", `${apiName}.ts`);
  writeFileSync(`${apiName}.ts`, tpl);
}

async function main() {
  const content = await httpGet(apiUrl);
  const doc = parse(content);

  const schemas = doc.components.schemas;
  for (const [key, value] of Object.entries(schemas)) {
    genFileDesc.schemas[key] = genSchema(key, value);
  }

  // paths
  const paths = doc.paths;
  for (const [key, value] of Object.entries(paths)) {
    genHttpApi(key, value);
  }
  render();
}

main();

function genHttpApi(path, desc) {
  const { get, post } = desc;
  // 仅支持 json请求
  const jsonRequest = post.requestBody.content["application/json"];
  if (!jsonRequest) {
    return;
  }
  const requestType = trimPrefix(
    jsonRequest.schema.$ref,
    "#/components/schemas/"
  );
  const responseType = trimPrefix(
    post.responses["200"].content["application/json"].schema.$ref,
    "#/components/schemas/"
  );
  let api = `export const ${camelCase(
    trimPrefix(path, prefix)
  )}Api = createApi<${requestType},${responseType}>('${path}')\n`;
  genFileDesc.apis[path] = api;
}

function genSchema(key, value) {
  let r = "";
  r += getTsObject(key, value);
  return r;
}

function getTsObject(name, desc) {
  let ts = `\nexport type ${name.replace(".", "")} = {\n`;
  const { properties } = desc;

  if (properties) {
    let props = "";
    for (let [key, value] of Object.entries(properties)) {
      // clean up key eg: user_id，omitempty
      key = key.replace(/,\s*omitempty/g, "");
      if (key.endsWith("omitempty")) {
        console.log(key);
      }
      let comment = value.description ? `  // ${value.description}\n` : "";
      props += `${comment}  ${key}: ${getTsType(value)};\n`;
    }
    if (props) {
      ts += props.slice(0, -1);
    }
  }

  ts += "\n}\n";
  return ts;
}

function getTsType(property) {
  switch (property.type) {
    case "integer":
      return "number";
    case "array":
      let arrRef = property.items.$ref;
      if (arrRef) {
        let refType = arrRef.split("/").pop();
        switch (refType) {
          case "string":
            return "string[]";
          case "int":
            return "number[]";
        }
        return `${refType.replace(".", "")}[]`;
      }
      return `${getTsType(property.items)}[]`;
    case "string":
      return "string";
    case "bool":
      return "boolean";
    default:
      let objRef = property.$ref;
      if (objRef) {
        const refType = objRef.split("/").pop();
        if (refType === "") {
          return "any";
        }
        if (refType === "json.RawMessage") {
          return "any";
        }
        if (refType === "bool") {
          return "boolean";
        }

        return refType.replace(".", "");
      }
      return property.type;
  }
}

function getDefaultValue(property) {
  switch (property.type) {
    case "integer":
      return "0";
    case "array":
      return "[]";
    default:
      let objRef = property.$ref;
      if (objRef) {
        let name = objRef.split("/").pop();
        if (name === "json.RawMessage") {
          return "null";
        }
        return `create${name}()`;
      }
      return '""';
  }
}
